### Podstawy przetwarzania dużych zbiorów danych - poziom 2 misja dodatkowa 4
#### Paulina Szczepaniak 247798
#### Jan Gluźniewicz 247665

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('df_merged_world_countries.csv')
df

,country_name,location_key,country_code,population,gdp_usd,area_sq_km,date,new_confirmed,cumulative_confirmed,new_deceased,...,area_sq_km_2,density_sq_km,growth_rate,world_population_percentage,gdp_in_1995,gdp_in_2000,gdp_in_2005,gdp_in_2010,gdp_in_2015,gdp_in_2016
0,Australia,AU,AUS,25499881,1.392681e+12,7741220,2022-01-18,72860.0,1836671.0,78.0,...,7692024,3.4032,1.0099,0.33,3.683917e+11,4.154462e+11,6.937641e+11,1.142877e+12,1.345383e+12,1.204616e+12
1,South Africa,ZA,ZAF,59308690,3.514316e+11,1219090,2022-01-02,3076.0,3475512.0,84.0,...,1221037,49.0517,1.0084,0.75,1.554603e+11,1.363619e+11,2.576714e+11,3.752981e+11,3.176107e+11,2.954562e+11
2,Peru,PE,PER,29381884,2.268481e+11,1285220,2021-03-30,10539.0,1577076.0,748.0,...,1285216,26.4933,1.0099,0.43,5.331279e+10,5.174475e+10,7.606061e+10,1.475289e+11,1.892121e+11,1.922073e+11
3,United States of America,US,USA,331002647,2.137442e+13,9831510,2021-09-08,167791.0,39489769.0,2068.0,...,9372610,36.0935,1.0038,4.24,7.664060e+12,1.028478e+13,1.309373e+13,1.496437e+13,1.812071e+13,1.862448e+13
4,Ethiopia,ET,ETH,114963583,9.610766e+10,1104300,2021-11-10,459.0,368106.0,22.0,...,1104300,111.7268,1.0257,1.55,7.663985e+09,8.242392e+09,1.240114e+10,2.993379e+10,6.446455e+10,7.237422e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227925,Croatia,HR,HRV,4076246,6.091759e+10,56590,2022-08-28,59.0,1211979.0,15.0,...,56594,71.2153,0.9927,0.05,2.238756e+10,2.177427e+10,4.541636e+10,5.966543e+10,4.892188e+10,5.071496e+10
227926,Austria,AT,AUT,8858775,4.551400e+11,83879,2022-07-27,9019.0,4756351.0,15.0,...,83871,106.5877,1.0020,0.11,2.410383e+11,1.967998e+11,3.159744e+11,3.918927e+11,3.820659e+11,3.908000e+11
227927,Argentina,AR,ARG,44938712,4.496634e+11,2780400,2021-10-10,382.0,5289547.0,15.0,...,2780400,16.3683,1.0052,0.57,2.580318e+11,2.842038e+11,1.987371e+11,4.236274e+11,5.847115e+11,5.454761e+11
227928,Sweden,SE,SWE,10230185,5.560253e+11,447430,2021-03-16,6786.0,731890.0,15.0,...,450295,23.4276,1.0079,0.13,2.640520e+11,2.598020e+11,3.890423e+11,4.883777e+11,4.979181e+11,5.144600e+11
227929,Belarus,BY,BLR,9449321,6.308046e+10,207600,2022-01-02,507.0,701699.0,15.0,...,207600,45.9295,0.9955,0.12,1.397263e+10,1.273686e+10,3.021009e+10,5.722249e+10,5.645473e+10,4.740722e+10

## Część 5
### Misja dodatkowa - Korelacja danych

##### Współczynnik korelacji przedstawia związek pomiędzy dwoma zmiennymi, co pozwala na zaobserwowanie potencjalnych zależności pomiędzy informacjami. 

##### Stwórz macierze korelacji, które przedstawią współczynniki korelacji dla każdej pary zmiennych:

##### 5.1. liczba nowych zachorowań, szczepień i zgonów, a liczba nowych zachorowań, szczepień i zgonów,

##### 5.2. liczba nowych zachorowań, szczepień, zgonów, a łączna liczba zachorowań, szczepień, zgonów,

##### 5.3. wskaźniki gospodarcze, a liczba nowych zachorowań, szczepień i zgonów,

##### 5.4. parametry demograficzne, a liczba nowych zachorowań, szczepień i zgonów,

##### 5.5. co najmniej 4 dodatkowe korelacje pomiędzy różnymi danymi.

##### Przeanalizuj swoje wyniki i omów otrzymane związki pomiędzy zmiennymi.